package com.example.daveai.ui.theme

import androidx.compose.ui.graphics.Color

// Warm Material 3 Palette (Orange/Amber/Cream)
// Light Palette
val primaryLight = Color(0xFF8B5000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDDB3)
val onPrimaryContainerLight = Color(0xFF2C1600)
val secondaryLight = Color(0xFF705B40)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFBDFAF)
val onSecondaryContainerLight = Color(0xFF251A04)
val tertiaryLight = Color(0xFF52643F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD5E9B9)
val onTertiaryContainerLight = Color(0xFF111F04)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F2)
val onBackgroundLight = Color(0xFF1F1B16)
val surfaceLight = Color(0xFFFFF8F2)
val onSurfaceLight = Color(0xFF1F1B16)
val surfaceVariantLight = Color(0xFFF0E0CF)
val onSurfaceVariantLight = Color(0xFF4F4539)
val outlineLight = Color(0xFF817567)

// Dark Palette
val primaryDark = Color(0xFFFFB951)
val onPrimaryDark = Color(0xFF4A2800)
val primaryContainerDark = Color(0xFF693C00)
val onPrimaryContainerDark = Color(0xFFFFDDB3)
val secondaryDark = Color(0xFFDEC48C)
val onSecondaryDark = Color(0xFF3E2E04)
val secondaryContainerDark = Color(0xFF564419)
val onSecondaryContainerDark = Color(0xFFFBDFAF)
val tertiaryDark = Color(0xFFB9CDA0)
val onTertiaryDark = Color(0xFF253515)
val tertiaryContainerDark = Color(0xFF3B4C29)
val onTertiaryContainerDark = Color(0xFFD5E9B9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1F1B16)
val onBackgroundDark = Color(0xFFEAE1D9)
val surfaceDark = Color(0xFF1F1B16)
val onSurfaceDark = Color(0xFFEAE1D9)
val surfaceVariantDark = Color(0xFF4F4539)
val onSurfaceVariantDark = Color(0xFFD3C4B4)
val outlineDark = Color(0xFF9C8F80)
